# Generated by Django 3.0.6 on 2020-06-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('payRate', models.IntegerField()),
                ('startDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=250)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=250)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Projects')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Profile')),
            ],
        ),
    ]
