# Generated by Django 3.0.6 on 2020-06-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0003_clients_invoices_projectnotes_projects_tasknotes_tasks_timers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Projects')),
                ('projectNotesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.ProjectNotes')),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Tasks')),
                ('taskNotesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.TaskNotes')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Profile')),
            ],
        ),
    ]
