# Generated by Django 3.0.6 on 2020-06-11 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0005_auto_20200610_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='workdiary',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='PyTraker.WorkDiary'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(),
        ),
    ]
