# Generated by Django 3.0.6 on 2020-06-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0007_auto_20200613_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='timers',
            name='totaltime',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
