# Generated by Django 3.0.6 on 2020-06-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0008_timers_totaltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timers',
            name='taskID',
        ),
        migrations.AddField(
            model_name='timers',
            name='projectID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Tasks'),
        ),
    ]
