# Generated by Django 3.0.6 on 2020-06-21 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0010_auto_20200616_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='timers',
            name='task',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Tasks'),
        ),
    ]
