# Generated by Django 3.0.6 on 2020-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0012_noteboard_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdiary',
            name='projectNotesID',
        ),
        migrations.RemoveField(
            model_name='workdiary',
            name='taskNotesID',
        ),
        migrations.AddField(
            model_name='workdiary',
            name='projectNotes',
            field=models.CharField(default='coming soon', max_length=2000),
        ),
        migrations.AddField(
            model_name='workdiary',
            name='taskNotes',
            field=models.CharField(default='coming soon', max_length=2000),
        ),
        migrations.AlterField(
            model_name='noteboard_note',
            name='note',
            field=models.TextField(),
        ),
    ]
