# Generated by Django 3.0.6 on 2020-06-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0014_auto_20200625_0445'),
        ('PyTraker', '0013_auto_20200624_1133'),
    ]

    operations = [
    ]
