# Generated by Django 3.0.6 on 2020-06-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0015_merge_20200626_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timers',
            name='totalhours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
